[package]
name = "internet_protocol"
version = "0.1.0"
authors = ["Adenylatcyclase <streicher1993@googlemails>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
